### ISSUE TITLE
503 Service Unavailable Backend Error

### ISSUE THREAD

**Issue by sprakash3** [GoogleCloudPlatform/DataflowJavaSDK-examples#3]
Hi there, 
I'm trying to run the DatastoreWordCount from the cookbook examples and encountered this exception.
I was hoping to get some help with this issue.

Stack Trace:

2016-02-15T17:43:36.674Z: Error:   (2edb046603c29179): com.google.api.services.datastore.client.DatastoreException: Backend Error
	at com.google.api.services.datastore.client.RemoteRpc.makeException(RemoteRpc.java:115)
	at com.google.api.services.datastore.client.RemoteRpc.call(RemoteRpc.java:81)
	at com.google.api.services.datastore.client.BaseDatastoreFactory$RemoteRpc.call(BaseDatastoreFactory.java:41)
	at com.google.api.services.datastore.client.Datastore.commit(Datastore.java:85)
	at com.google.cloud.dataflow.sdk.io.DatastoreIO$DatastoreWriter.flushBatch(DatastoreIO.java:768)
	at com.google.cloud.dataflow.sdk.io.DatastoreIO$DatastoreWriter.write(DatastoreIO.java:726)
	at com.google.cloud.dataflow.sdk.io.DatastoreIO$DatastoreWriter.write(DatastoreIO.java:668)
	at com.google.cloud.dataflow.sdk.io.Write$Bound$2.processElement(Write.java:168)
Caused by: com.google.api.client.http.HttpResponseException: 503 Service Unavailable
Backend Error
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1054)
	at com.google.api.services.datastore.client.RemoteRpc.call(RemoteRpc.java:78)
	at com.google.api.services.datastore.client.BaseDatastoreFactory$RemoteRpc.call(BaseDatastoreFactory.java:41)
	at com.google.api.services.datastore.client.Datastore.commit(Datastore.java:85)
	at com.google.cloud.dataflow.sdk.io.DatastoreIO$DatastoreWriter.flushBatch(DatastoreIO.java:768)
	at com.google.cloud.dataflow.sdk.io.DatastoreIO$DatastoreWriter.write(DatastoreIO.java:726)
	at com.google.cloud.dataflow.sdk.io.DatastoreIO$DatastoreWriter.write(DatastoreIO.java:668)
	at com.google.cloud.dataflow.sdk.io.Write$Bound$2.processElement(Write.java:168)
	at com.google.cloud.dataflow.sdk.util.DoFnRunner.invokeProcessElement(DoFnRunner.java:189)
	at com.google.cloud.dataflow.sdk.util.DoFnRunner.processElement(DoFnRunner.java:171)
	at com.google.cloud.dataflow.sdk.runners.worker.ParDoFnBase.processElement(ParDoFnBase.java:213)
	at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:53)
	at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52)
	at com.google.cloud.dataflow.sdk.runners.worker.ParDoFnBase$1.output(ParDoFnBase.java:174)
	at com.google.cloud.dataflow.sdk.util.DoFnRunner$DoFnContext.outputWindowedValue(DoFnRunner.java:333)
	at com.google.cloud.dataflow.sdk.util.DoFnRunner$DoFnProcessContext.output(DoFnRunner.java:487)
	at com.google.cloud.dataflow.examples.cookbook.DatastoreWordCount$CreateEntityFn.processElement(DatastoreWordCount.java:148)
	at com.google.cloud.dataflow.sdk.util.DoFnRunner.invokeProcessElement(DoFnRunner.java:189)
	at com.google.cloud.dataflow.sdk.util.DoFnRunner.processElement(DoFnRunner.java:171)
	at com.google.cloud.dataflow.sdk.runners.worker.ParDoFnBase.processElement(ParDoFnBase.java:213)
	at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:53)
	at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:223)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.start(ReadOperation.java:169)
	at com.google.cloud.dataflow.sdk.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:69)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.executeWork(DataflowWorker.java:254)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.doWork(DataflowWorker.java:191)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:144)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:180)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:161)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:148)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thanks!

**Comment by francesperry** [comment]
Could you provide the job ID so we can investigate? Thanks!

**Comment by sprakash3** [comment]
Here's the id - 2016-02-15_09_01_55-13123052380211589294
Thanks

**Comment by francesperry** [comment]
The Datastore datasetId needs to be the same as your project id. (See https://cloud.google.com/datastore/docs/activate.) 

I've confirmed that I can repro the error by choosing a datasetId that is different from my project id. Please let us know if if setting --dataset=<project_id> doesn't fix your issue.

Additionally, we'll investigate if there's something better we can do to validate datasetId and provide a clearer error message.

Thanks!
