### ISSUE TITLE
 Quickstart Using Java and Apache Maven error

### ISSUE THREAD

**Issue by alphayang** [GoogleCloudPlatform/DataflowJavaSDK-examples#5]
Following get start tutorial, got error whether JDK or OpenJDK with Cloud Shell:

mvn compile exec:java \
-Dexec.mainClass=com.google.cloud.dataflow.examples.WordCount \
-Dexec.args="--project=alpha-life-line \
--stagingLocation=word-count \
--runner=BlockingDataflowPipelineRunner"

[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ first-dataflow ---
[WARNING] 
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to construct instance from factory method BlockingDataflowPipelineRunner#fromOptions(interface com.google.cloud.dataflow.sdk.options.PipelineOptions)
        at com.google.cloud.dataflow.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:233)
        at com.google.cloud.dataflow.sdk.util.InstanceBuilder.build(InstanceBuilder.java:162)
        at com.google.cloud.dataflow.sdk.runners.PipelineRunner.fromOptions(PipelineRunner.java:57)
        at com.google.cloud.dataflow.sdk.Pipeline.create(Pipeline.java:134)
        at com.example.WordCount.main(WordCount.java:193)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.cloud.dataflow.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:222)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: 
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
        at com.google.api.client.json.JsonParser.parseArray(JsonParser.java:648)
        at com.google.api.client.json.JsonParser.parseArray(JsonParser.java:628)
        at com.google.api.client.json.JsonParser.parseArray(JsonParser.java:597)
        at com.google.api.client.json.JsonParser.parseArray(JsonParser.java:577)
        at com.google.api.client.googleapis.auth.oauth2.CloudShellCredential.executeRefreshToken(CloudShellCredential.java:88)
        at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
        at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
        at com.google.cloud.hadoop.util.ChainingHttpRequestInitializer$2.intercept(ChainingHttpRequestInitializer.java:98)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.google.cloud.hadoop.util.ResilientOperation$AbstractGoogleClientRequestExecutor.call(ResilientOperation.java:166)
        at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:66)
        at com.google.cloud.dataflow.sdk.util.GcsUtil.bucketExists(GcsUtil.java:325)
        at com.google.cloud.dataflow.sdk.util.GcsUtil.bucketExists(GcsUtil.java:312)
        at com.google.cloud.dataflow.sdk.util.DataflowPathValidator.verifyPathIsAccessible(DataflowPathValidator.java:79)
        at com.google.cloud.dataflow.sdk.util.DataflowPathValidator.validateOutputFilePrefixSupported(DataflowPathValidator.java:62)
        at com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner.fromOptions(DataflowPipelineRunner.java:255)
        at com.google.cloud.dataflow.sdk.runners.BlockingDataflowPipelineRunner.fromOptions(BlockingDataflowPipelineRunner.java:82)
        ... 15 more
Caused by: java.lang.IllegalArgumentException: expected numeric type but got class java.lang.String
        at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:844)
        ... 35 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
        at java.lang.reflect.Method.invoke(Method.java:606)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.595 s
[INFO] Finished at: 2016-06-10T16:52:53+08:00
[INFO] Final Memory: 14M/33M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project first-dataflow: An exception occured while executing the Java class. nu
ll: InvocationTargetException: Failed to construct instance from factory method BlockingDataflowPipelineRunner#fromOptions(interface com.google.cloud.dataflow.sdk.options.Pip
elineOptions): IllegalArgumentException: expected numeric type but got class java.lang.String -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lukecwik** [comment]
This is a known issue, we have a 1.6.0 release that is expected to be available shortly and should resolve this issue.

**Comment by davorbonaci** [comment]
Sounds like this is already fixed. Closing. Please reopen if you encounter this issue again!
